services:
  indexdb:
    container_name: thehive_database
    image: surrealdb/surrealdb:latest
    ports:
      - '8000:8000'
    volumes:
      - shared-data:/data # don't change this!
    command: start --bind 0.0.0.0:8000 --user ${dbRootUser} --pass ${dbRootPass} surrealkv:///data/AppFiles/surreal.db
    networks:
      - thehive_network

  aiserver:
    container_name: thehive
    image: thehive
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - '3000:3000'
    depends_on:
      - indexdb
      - n8n 
    volumes:
      - shared-data:/data # don't change this!
    networks:
      - thehive_network

  n8n:
    container_name: thehive_n8n
    image: n8nio/n8n:latest
    ports:
      - '5678:5678'
    environment:
      - N8N_USER_FOLDER=/data/AppFiles/n8n_data 
    volumes:
      - shared-data:/data # don't change this!
    networks:
      - thehive_network
    # restart: always

volumes:
  shared-data:
    driver: local
    driver_opts:
      type: none
      device: ${knowledgebaseHostURL}
      o: bind

networks:
  thehive_network:
    driver: bridge