services:
  indexdb:
    container_name: botzybee_database
    image: surrealdb/surrealdb:latest
    ports:
      - '8000:8000'
    volumes:
      - shared-data:/data # don't change this!
    command: start --bind 0.0.0.0:8000 --user ${dbRootUser} --pass ${dbRootPass} surrealkv:///data/AppFiles/surreal.db
    #restart: always
    networks:
      - botzybee_network

  aiserver:
    container_name: botzybee
    image: botzybee
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - '3000:3000'
    depends_on:
      - indexdb
    volumes:
      - shared-data:/data # don't change this!
    # restart: always
    networks:
      - botzybee_network

volumes:
  shared-data:
    driver: local
    # below binds to a host path
    driver_opts:
      type: none
      device: ${knowledgebaseHostURL} # URL on the host device
      o: bind

networks:
  botzyai_network:
    driver: bridge
